theme: minima
title: Dev V. Patram Portfolio
description: Engineering × AI | Intelligent Systems & Power Optimization
url: "https://devpatram.github.io"
baseurl: "/engineering-ai-portfolio"

markdown: kramdown

# Disable Minima’s automatic top links
header_pages: []

include:
  - AICoPilot
  - WeeklyStatusGem
  - Compliance-Automation
  - PowerOptimization
  - AI-ML-Labs

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
